name: flutter_todos
description: An example todos app that showcases riverpod state management patterns.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  riverpod_annotation: ^2.3.5
  local_storage_todos_api:
    path: packages/local_storage_todos_api
  todos_api:
    path: packages/todos_api
  todos_repository:
    path: packages/todos_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  custom_lint: ^0.6.2
  mockingjay: ^0.5.0
  mocktail: ^1.0.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  generate: true
